export const ADDINGINGRIDENTS = "ADDINGINGRIDENTS";
export const REMOVINGINGRIDENTS = "REMOVINGINGRIDENTS";
export const STORINGINGRIDNETS = "STORINGINGRIDNETS";
export const ERROR = "ERROR";
export const STORINGDATATOSERVER = "STORINGDATATOSERVER";
export const ERRORONSTORINGDATATOSERVER = "ERRORONSTORINGDATATOSERVER";
export const LOADING = "LOADING";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";
export const AUTH_EXPIRY = "AUTH_EXPIRY";

export const REDIRECTING = "REDIRECTING";
export const ISTOKENPRESENTINLOCAL = "ISTOKENPRESENTINLOCAL";
