export const ADDINGINGRIDENTS = "ADDINGINGRIDENTS";
export const REMOVINGINGRIDENTS = "REMOVINGINGRIDENTS";
export const STORINGINGRIDNETS = "STORINGINGRIDNETS";
export const ERROR = "ERROR";
export const STORINGDATATOSERVER = "STORINGDATATOSERVER";
export const ERRORONSTORINGDATATOSERVER = "ERRORONSTORINGDATATOSERVER";
export const LOADING = "LOADING";
